/**
 * Go testing renderer
 * Produces Go test files using the standard `testing` package
 * (func TestXxx(t *testing.T)).
 *
 * One file per (domain, requirement) group; the package name is derived from
 * the domain so the file compiles as a self-contained test package.
 */

import type { ParsedScenario } from '../../../types/test-generator.js';
import type { ThenMatch } from '../then-matchers.js';
import { buildMetadataTag, buildRelatedImpl, buildAutoGeneratedWarning, toPascalCase } from './shared.js';

/** Go package names must be lowercase identifiers (letters/digits, no leading digit). */
function toGoPackage(domain: string): string {
  const cleaned = domain.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (!cleaned || /^[0-9]/.test(cleaned)) return `spec${cleaned}`;
  return cleaned;
}

export function renderGotest(
  domain: string,
  requirement: string,
  scenarios: ParsedScenario[],
  matchesByScenario: ThenMatch[][]
): string {
  const blocks: string[] = [];
  blocks.push(`package ${toGoPackage(domain)}_test`);
  blocks.push('');
  blocks.push('import "testing"');
  blocks.push('');

  for (let i = 0; i < scenarios.length; i++) {
    const s = scenarios[i];
    const matches = matchesByScenario[i];
    const funcName = `Test${toPascalCase(requirement)}${toPascalCase(s.scenarioName)}`;

    const bodyLines: string[] = [];
    for (const g of s.given) bodyLines.push(`// GIVEN: ${g}`);
    for (const w of s.when) bodyLines.push(`// WHEN: ${w}`);
    for (const t of s.then) bodyLines.push(`// THEN: ${t}`);

    const relatedImpl = buildRelatedImpl('//', s.mappedFunctions);
    if (relatedImpl.length > 0) {
      bodyLines.push('');
      bodyLines.push(...relatedImpl);
    }

    bodyLines.push('');
    const hasHeuristic = matches.some((m) => m.fromPattern);
    if (hasHeuristic) bodyLines.push(buildAutoGeneratedWarning('//'));
    for (const match of matches) {
      for (const line of match.lines) {
        bodyLines.push(line);
      }
    }

    blocks.push(buildMetadataTag('//', s));
    blocks.push(`func ${funcName}(t *testing.T) {`);
    blocks.push(...bodyLines.map((l) => (l ? `\t${l}` : '')));
    blocks.push('}');
    blocks.push('');
  }

  return blocks.join('\n');
}
