/**
 * JUnit 5 (Jupiter) renderer
 * Produces Java test files using the JUnit 5 @Test / Assertions API.
 *
 * One class per (domain, requirement) group; the class name matches the
 * generated file's basename (a Java source-file requirement) — see
 * outputFilename() in test-generator.ts, which emits `<Requirement>Test.java`.
 */

import type { ParsedScenario } from '../../../types/test-generator.js';
import type { ThenMatch } from '../then-matchers.js';
import { buildMetadataTag, buildRelatedImpl, buildAutoGeneratedWarning, toPascalCase } from './shared.js';

export function renderJunit(
  _domain: string,
  requirement: string,
  scenarios: ParsedScenario[],
  matchesByScenario: ThenMatch[][]
): string {
  const className = `${toPascalCase(requirement)}Test`;

  const blocks: string[] = [];
  blocks.push('import org.junit.jupiter.api.Test;');
  blocks.push('import static org.junit.jupiter.api.Assertions.*;');
  blocks.push('');
  blocks.push(`class ${className} {`);

  for (let i = 0; i < scenarios.length; i++) {
    const s = scenarios[i];
    const matches = matchesByScenario[i];
    const methodName = `test${toPascalCase(s.scenarioName)}`;

    const bodyLines: string[] = [];
    for (const g of s.given) bodyLines.push(`// GIVEN: ${g}`);
    for (const w of s.when) bodyLines.push(`// WHEN: ${w}`);
    for (const t of s.then) bodyLines.push(`// THEN: ${t}`);

    const relatedImpl = buildRelatedImpl('//', s.mappedFunctions);
    if (relatedImpl.length > 0) {
      bodyLines.push('');
      bodyLines.push(...relatedImpl);
    }

    bodyLines.push('');
    const hasHeuristic = matches.some((m) => m.fromPattern);
    if (hasHeuristic) bodyLines.push(buildAutoGeneratedWarning('//'));
    for (const match of matches) {
      for (const line of match.lines) {
        bodyLines.push(line);
      }
    }

    blocks.push('');
    blocks.push(`    ${buildMetadataTag('//', s)}`);
    blocks.push(`    @Test`);
    blocks.push(`    void ${methodName}() {`);
    blocks.push(...bodyLines.map((l) => (l ? `        ${l}` : '')));
    blocks.push(`    }`);
  }

  blocks.push('}');
  blocks.push('');

  return blocks.join('\n');
}
