/**
 * Codebase Digest — generates .openlore/CODEBASE.md
 *
 * A compact, agent-readable Markdown summary of the codebase produced by
 * `openlore analyze`.  Designed to be included in CLAUDE.md / .clinerules
 * so agents absorb architectural context passively at session start, without
 * needing to call any MCP tool.
 *
 * Content:
 *   - Entry points (functions with no internal callers)
 *   - Critical hubs (highest fan-in functions)
 *   - Spec domains (if openspec/specs/ exists)
 *   - Most coupled files (high in-degree in dependency graph)
 *   - God functions / oversized orchestrators
 *   - Layer violations (if any)
 */

import { writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { LLMContext } from './artifact-generator.js';
import type { DependencyGraphResult } from './dependency-graph.js';
import { languageCoverageMatrix, renderCoverageMatrixMarkdown } from './language-support.js';

// ============================================================================
// TYPES
// ============================================================================

interface DigestOptions {
  /** Absolute path to the project root */
  rootPath: string;
  /** Absolute path to the .openlore/analysis/ output directory */
  outputDir: string;
  /** Max entry points to list */
  maxEntryPoints?: number;
  /** Max hub functions to list */
  maxHubs?: number;
  /** Max god functions to list */
  maxGodFunctions?: number;
  /** Max most-coupled files to list */
  maxCoupledFiles?: number;
}

// ============================================================================
// HELPERS
// ============================================================================

function rel(absPath: string, rootPath: string): string {
  return absPath.startsWith(rootPath)
    ? absPath.slice(rootPath.length).replace(/^\//, '')
    : absPath;
}

/** Extract per-file coupling from pre-computed node metrics */
function fileCoupling(depGraph: DependencyGraphResult | null): Array<{ path: string; importedBy: number; imports: number }> {
  if (!depGraph) return [];
  return depGraph.nodes
    .map(n => ({
      path: n.file?.path ?? n.id,
      importedBy: n.metrics?.inDegree ?? 0,
      imports: n.metrics?.outDegree ?? 0,
    }))
    .sort((a, b) => b.importedBy - a.importedBy);
}

// ============================================================================
// MAIN EXPORT
// ============================================================================

/**
 * Generate `.openlore/CODEBASE.md` from cached analysis artifacts.
 *
 * Non-fatal: logs a warning and returns false if generation fails.
 */
export async function generateCodebaseDigest(
  llmContext: LLMContext,
  depGraph: DependencyGraphResult | null,
  opts: DigestOptions,
): Promise<boolean> {
  try {
    const {
      rootPath,
      outputDir,
      maxEntryPoints = 8,
      maxHubs = 10,
      maxGodFunctions = 5,
      maxCoupledFiles = 8,
    } = opts;

    const cg = llmContext.callGraph;
    const lines: string[] = [];
    const now = new Date().toISOString().slice(0, 10);

    lines.push(`# Codebase — architecture digest`);
    lines.push(`> Generated by openlore analyze on ${now}. Re-run after significant refactors.`);
    lines.push(`> Add this file to CLAUDE.md or .clinerules so agents absorb it at session start.`);
    lines.push('');

    // ── Overview ──────────────────────────────────────────────────────────────
    if (cg) {
      // Production functions only: cg.nodes also carries test and external (library)
      // nodes so the test-impact tools can use them. The digest describes the
      // production surface, so exclude both — otherwise test helpers and stdlib
      // calls inflate the counts and leak into the god-function list (e.g. a Java
      // `FooTest.checkOption` showing up as an orchestrator).
      const prodNodes = cg.nodes.filter(n => !n.isTest && !n.isExternal);
      // `stats.totalEdges` counts ALL `calls` edges — including test-caller and
      // external-callee edges — so labeling it "internal" next to the production-only
      // function count mixes two populations under one qualifier. Count only edges
      // whose BOTH endpoints are production nodes, matching `prodNodes` above.
      const prodNodeIds = new Set(prodNodes.map(n => n.id));
      const internalEdges = cg.edges.filter(
        e => (!e.kind || e.kind === 'calls') && prodNodeIds.has(e.callerId) && prodNodeIds.has(e.calleeId)
      ).length;
      lines.push('## Overview');
      lines.push(`- **${prodNodes.length}** functions / methods analyzed`);
      lines.push(`- **${internalEdges}** internal call edges`);
      lines.push(`- **${cg.entryPoints?.length ?? 0}** entry points (no internal callers)`);
      lines.push(`- **${cg.hubFunctions?.length ?? 0}** hub functions (high fan-in)`);
      if (cg.stats?.avgFanIn !== undefined) {
        lines.push(`- avg fan-in: **${cg.stats.avgFanIn.toFixed(2)}**, avg fan-out: **${cg.stats.avgFanOut.toFixed(2)}**`);
      }
      lines.push('');
    }

    // ── Language coverage ─────────────────────────────────────────────────────
    // A deterministic capability matrix over the repo's detected languages, so a
    // quiet structural result is interpretable: "·" means the capability is not
    // backed for that language (fail-soft), not that there were no matches.
    if (cg) {
      const detected = [...new Set(
        cg.nodes.filter(n => !n.isExternal && n.language && n.language !== 'unknown').map(n => n.language),
      )].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
      if (detected.length > 0) {
        lines.push('## Language coverage');
        lines.push('What OpenLore extracts per detected language (`✓` backed, `·` fail-soft / not claimed). A `·` cell means a quiet result for that capability is "unsupported here", not "nothing found".');
        lines.push('');
        lines.push(...renderCoverageMatrixMarkdown(languageCoverageMatrix(detected)));
        lines.push('');
        lines.push('> Query this at runtime with the `get_language_support` MCP tool (opt-in). See the "add a language" checklist in the docs.');
        lines.push('');
      }
    }

    // ── Entry points ──────────────────────────────────────────────────────────
    if (cg?.entryPoints?.length) {
      lines.push('## Entry points');
      lines.push('Functions with no internal callers — the natural starting point for any task.');
      lines.push('');
      lines.push('| Function | File | fanOut |');
      lines.push('|----------|------|--------|');
      for (const ep of cg.entryPoints.slice(0, maxEntryPoints)) {
        const file = rel(ep.filePath, rootPath);
        const name = ep.className ? `${ep.className}.${ep.name}` : ep.name;
        lines.push(`| \`${name}\` | \`${file}\` | ${ep.fanOut} |`);
      }
      if (cg.entryPoints.length > maxEntryPoints) {
        lines.push(`| … | *(${cg.entryPoints.length - maxEntryPoints} more)* | |`);
      }
      lines.push('');
    }

    // ── Critical hubs ─────────────────────────────────────────────────────────
    if (cg?.hubFunctions?.length) {
      const sorted = [...cg.hubFunctions].sort((a, b) => b.fanIn - a.fanIn);
      lines.push('## Critical hubs');
      lines.push('Most-called functions — modifying these has the widest blast radius.');
      lines.push('');
      lines.push('| Function | File | fanIn | fanOut |');
      lines.push('|----------|------|-------|--------|');
      for (const hub of sorted.slice(0, maxHubs)) {
        const file = rel(hub.filePath, rootPath);
        const name = hub.className ? `${hub.className}.${hub.name}` : hub.name;
        lines.push(`| \`${name}\` | \`${file}\` | ${hub.fanIn} | ${hub.fanOut} |`);
      }
      if (sorted.length > maxHubs) {
        lines.push(`| … | *(${sorted.length - maxHubs} more)* | | |`);
      }
      lines.push('');
    }

    // ── God functions ─────────────────────────────────────────────────────────
    if (cg?.nodes?.length) {
      // Production functions only — test helpers and external (library) nodes are
      // not orchestrators of this codebase (see Overview note above).
      const gods = cg.nodes
        .filter(n => !n.isTest && !n.isExternal && n.fanOut >= 8)
        .sort((a, b) => b.fanOut - a.fanOut)
        .slice(0, maxGodFunctions);

      if (gods.length > 0) {
        lines.push('## God functions (high fan-out orchestrators)');
        lines.push('These functions coordinate many downstream calls — extend them carefully.');
        lines.push('');
        lines.push('| Function | File | fanOut |');
        lines.push('|----------|------|--------|');
        for (const g of gods) {
          const file = rel(g.filePath, rootPath);
          const name = g.className ? `${g.className}.${g.name}` : g.name;
          lines.push(`| \`${name}\` | \`${file}\` | ${g.fanOut} |`);
        }
        lines.push('');
      }
    }

    // ── Most coupled files ────────────────────────────────────────────────────
    const coupled = fileCoupling(depGraph);
    if (coupled.length > 0) {
      const top = coupled.filter(f => f.importedBy >= 3).slice(0, maxCoupledFiles);
      if (top.length > 0) {
        lines.push('## Most imported files');
        lines.push('High in-degree files — changes here ripple widely. Prefer extending over modifying.');
        lines.push('');
        lines.push('| File | imported by | imports |');
        lines.push('|------|-------------|---------|');
        for (const f of top) {
          lines.push(`| \`${f.path}\` | ${f.importedBy} | ${f.imports} |`);
        }
        lines.push('');
      }
    }

    // ── Layer violations ──────────────────────────────────────────────────────
    if (cg?.layerViolations?.length) {
      lines.push('## Layer violations');
      lines.push('These cross-layer call patterns indicate architecture drift.');
      lines.push('');
      for (const v of cg.layerViolations.slice(0, 5)) {
        lines.push(`- \`${v.callerId}\` → \`${v.calleeId}\` *(${v.callerLayer} → ${v.calleeLayer})*`);
      }
      if (cg.layerViolations.length > 5) {
        lines.push(`- … (${cg.layerViolations.length - 5} more violations)`);
      }
      lines.push('');
    }

    // ── Spec domains ──────────────────────────────────────────────────────────
    const specsDir = join(rootPath, 'openspec', 'specs');
    if (existsSync(specsDir)) {
      try {
        const entries = await readdir(specsDir);
        // Sort before emission: raw `readdir` order is platform-dependent, so an
        // unsorted list would make the digest bytes vary across machines.
        const domains = entries
          .filter(e => existsSync(join(specsDir, e, 'spec.md')))
          .sort((a, b) => a.localeCompare(b));
        if (domains.length > 0) {
          lines.push('## Spec domains');
          lines.push('OpenSpec domains available for this project. Use `search_specs` or `get_spec` to query them.');
          lines.push('');
          for (const d of domains) {
            lines.push(`- \`${d}\` — \`openspec/specs/${d}/spec.md\``);
          }
          lines.push('');
        }
      } catch { /* non-fatal */ }
    }

    // ── MCP workflow ─────────────────────────────────────────────────────────────────────────────
    lines.push('## openlore MCP workflow');
    lines.push('');
    lines.push('**Follow this sequence for every task:**');
    lines.push('');
    lines.push('1. **`orient "<task description>"`** — always start here. Returns relevant functions, files, spec domains, call paths, and insertion points in one call.');
    lines.push('2. **If the task involves data models, APIs, or config** — call the relevant inventory tool:');
    lines.push('   `get_schema_inventory` · `get_route_inventory` · `get_env_vars` · `get_ui_component_inventory` · `get_middleware_inventory`');
    lines.push('3. **If debugging a call flow** ("how does X reach Y?") — `trace_execution_path`');
    lines.push('4. **Before modifying a function** — `get_subgraph` to understand blast radius');
    lines.push('5. **Before opening a PR** — `check_spec_drift`');
    lines.push('');
    lines.push("**On-demand** (when orient's results aren't enough):");
    lines.push('`search_code` · `suggest_insertion_points` · `get_spec <domain>` · `search_specs` · `analyze_impact` · `get_function_body` · `get_function_skeleton`');

    const digest = lines.join('\n') + '\n';
    await writeFile(join(outputDir, 'CODEBASE.md'), digest, 'utf-8');
    return true;
  } catch {
    return false;
  }
}
