import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SpecVectorIndex } from './spec-vector-index.js';
import type { EmbeddingService } from './embedding-service.js';

// ============================================================================
// FIXTURES
// ============================================================================

const SAMPLE_SPEC_AUTH = `# Auth Specification

> Generated by openlore v1.0.0 on 2026-01-01
> Source files: src/auth/index.ts

## Purpose

Handles user authentication and session management.

## Entities

### User

Represents an authenticated user.

## Requirements

### Requirement: ValidateEmail

The system SHALL validate email format before registration.

#### Scenario: ValidEmail
- **GIVEN** A valid email address
- **WHEN** validateEmail is called
- **THEN** Returns true

#### Scenario: InvalidEmail
- **GIVEN** An invalid email address
- **WHEN** validateEmail is called
- **THEN** Returns false

### Requirement: Login

The system SHALL authenticate users with email and password.

## Design

JWT tokens are used for session management.
`;

const SAMPLE_SPEC_CRAWLER = `# Crawler Specification

## Purpose

Web crawling and content extraction.

## Requirements

### Requirement: Fetch

The system SHALL fetch pages via HTTP with retry logic.
`;

const SAMPLE_MAPPING = JSON.stringify({
  mappings: [
    {
      requirement: 'validateEmail',
      domain: 'auth',
      specFile: './openspec/specs/auth/spec.md',
      functions: [
        { name: 'validateEmail', file: 'src/auth/validator.ts', line: 10, kind: 'function', confidence: 'llm' },
        { name: 'UserService', file: 'src/auth/user.service.ts', line: 1, kind: 'class', confidence: 'heuristic' },
      ],
    },
    {
      requirement: 'login',
      domain: 'auth',
      specFile: './openspec/specs/auth/spec.md',
      functions: [
        { name: '*', file: 'src/auth/index.ts', line: 1, kind: 'unknown', confidence: 'heuristic' },
      ],
    },
    {
      requirement: 'fetch',
      domain: 'crawler',
      specFile: './openspec/specs/crawler/spec.md',
      functions: [
        { name: 'fetchPage', file: 'src/crawler/fetcher.ts', line: 5, kind: 'function', confidence: 'llm' },
      ],
    },
  ],
});

// ============================================================================
// MOCK
// ============================================================================

const DIM = 8;

function makeVector(seed: number): number[] {
  return Array.from({ length: DIM }, (_, i) => ((seed + i) % 10) * 0.1);
}

function makeMockEmbedSvc(): EmbeddingService {
  const callCount = 0;
  return {
    embed: vi.fn().mockImplementation(async (texts: string[]) =>
      texts.map((_, i) => makeVector(callCount + i++))
    ),
  } as unknown as EmbeddingService;
}

// ============================================================================
// HELPERS
// ============================================================================

async function createSpecsDir(
  root: string,
  specs: Record<string, string>
): Promise<string> {
  const specsDir = join(root, 'openspec', 'specs');
  for (const [domain, content] of Object.entries(specs)) {
    const domainDir = join(specsDir, domain);
    await mkdir(domainDir, { recursive: true });
    await writeFile(join(domainDir, 'spec.md'), content, 'utf-8');
  }
  return specsDir;
}

// ============================================================================
// TESTS
// ============================================================================

describe('SpecVectorIndex', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'openlore-spec-vector-test-'));
  });

  // --------------------------------------------------------------------------
  // exists()
  // --------------------------------------------------------------------------

  describe('exists()', () => {
    it('returns false when no index has been built', () => {
      expect(SpecVectorIndex.exists(tmpDir)).toBe(false);
    });

    it('returns true after build()', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(SpecVectorIndex.exists(tmpDir)).toBe(true);
    });
  });

  // --------------------------------------------------------------------------
  // build()
  // --------------------------------------------------------------------------

  describe('build()', () => {
    it('throws a "present but empty" error when the spec dir exists but has no specs', async () => {
      const emptyDir = join(tmpDir, 'empty-specs');
      await mkdir(emptyDir, { recursive: true });
      const embedSvc = makeMockEmbedSvc();
      await expect(SpecVectorIndex.build(tmpDir, emptyDir, embedSvc)).rejects.toThrow(
        'exists but contains no spec.md files'
      );
    });

    it('throws a "does not exist" error when the spec dir is missing', async () => {
      const embedSvc = makeMockEmbedSvc();
      await expect(
        SpecVectorIndex.build(tmpDir, join(tmpDir, 'nope-specs'), embedSvc)
      ).rejects.toThrow('does not exist');
    });

    it('returns the number of indexed sections', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      // auth spec has: purpose, entities, requirements (2 items), design = 5 sections
      expect(recordCount).toBeGreaterThan(0);
    });

    it('calls embed once with all section texts', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(embedSvc.embed).toHaveBeenCalledTimes(1);
    });

    it('handles multiple domains', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        crawler: SAMPLE_SPEC_CRAWLER,
      });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(recordCount).toBeGreaterThan(3); // both specs contribute sections
    });

    it('enriches records with linkedFiles from mapping.json', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const mappingPath = join(tmpDir, 'mapping.json');
      await writeFile(mappingPath, SAMPLE_MAPPING, 'utf-8');

      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc, mappingPath);

      // Search for the validateEmail requirement
      const results = await SpecVectorIndex.search(tmpDir, 'email validation', embedSvc, { limit: 20 });
      const emailReq = results.find(r => r.record.id === 'auth.validateEmail');
      expect(emailReq).toBeDefined();
      expect(emailReq!.record.linkedFiles).toContain('src/auth/validator.ts');
      expect(emailReq!.record.linkedFiles).toContain('src/auth/user.service.ts');
    });

    it('filters out wildcard (*) entries from linkedFiles', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const mappingPath = join(tmpDir, 'mapping.json');
      await writeFile(mappingPath, SAMPLE_MAPPING, 'utf-8');

      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc, mappingPath);

      const results = await SpecVectorIndex.search(tmpDir, 'login authentication', embedSvc, { limit: 20 });
      const loginReq = results.find(r => r.record.id === 'auth.login');
      // login mapping only has wildcard (*) → linkedFiles should be empty
      expect(loginReq?.record.linkedFiles ?? []).not.toContain('*');
    });

    it('overwrites existing index on second build', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      await expect(SpecVectorIndex.build(tmpDir, specsDir, embedSvc)).resolves.not.toThrow();
    });

    it('proceeds without enrichment if mapping.json is missing', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(
        tmpDir,
        specsDir,
        embedSvc,
        join(tmpDir, 'nonexistent-mapping.json')
      );
      expect(recordCount).toBeGreaterThan(0);
    });
  });

  // --------------------------------------------------------------------------
  // search()
  // --------------------------------------------------------------------------

  describe('search()', () => {
    it('returns up to limit results', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any query', embedSvc, { limit: 2 });
      expect(results.length).toBeLessThanOrEqual(2);
    });

    it('each result has a score field', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'email', embedSvc, { limit: 10 });
      for (const r of results) {
        expect(typeof r.score).toBe('number');
      }
    });

    it('result records have linkedFiles as string[]', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'query', embedSvc, { limit: 10 });
      for (const r of results) {
        expect(Array.isArray(r.record.linkedFiles)).toBe(true);
      }
    });

    it('filters by domain', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        crawler: SAMPLE_SPEC_CRAWLER,
      });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        domain: 'auth',
      });
      for (const r of results) {
        expect(r.record.domain).toBe('auth');
      }
    });

    it('filters by section', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        section: 'requirements',
      });
      for (const r of results) {
        expect(r.record.section).toBe('requirements');
      }
    });

    it('throws when index does not exist', async () => {
      const embedSvc = makeMockEmbedSvc();
      await expect(
        SpecVectorIndex.search(tmpDir, 'query', embedSvc, { limit: 5 })
      ).rejects.toThrow('No spec index found');
    });

    it('returns empty array when domain filter matches nothing', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        domain: 'nonexistent-domain',
      });
      expect(results).toHaveLength(0);
    });
  });

  // --------------------------------------------------------------------------
  // Markdown parser (tested indirectly via build + search)
  // --------------------------------------------------------------------------

  describe('Markdown parsing', () => {
    it('assigns correct section type to Requirements H3 items', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'validate email', embedSvc, {
        limit: 20,
        section: 'requirements',
      });
      expect(results.length).toBeGreaterThan(0);
      const req = results.find(r => r.record.id.includes('validateEmail'));
      expect(req).toBeDefined();
      expect(req!.record.section).toBe('requirements');
    });

    it('assigns correct section type to Purpose H2', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'authentication session', embedSvc, {
        limit: 20,
        section: 'purpose',
      });
      expect(results.length).toBeGreaterThan(0);
    });

    it('builds id as domain.requirementKey for requirements', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'validate', embedSvc, { limit: 20 });
      const req = results.find(r => r.record.id === 'auth.validateEmail');
      expect(req).toBeDefined();
    });
  });
});
