/**
 * SpecVectorIndex
 *
 * Builds and queries a LanceDB vector index over OpenSpec spec files.
 * Each record represents a logical section (requirement, purpose, design note...)
 * parsed from the Markdown spec files.
 *
 * Storage: <outputDir>/vector-index/  (same LanceDB folder as VectorIndex, different table)
 * Table name: "specs"
 *
 * Usage:
 *   // Build (or rebuild)
 *   await SpecVectorIndex.build(outputDir, specsDir, mappingJson, embedSvc);
 *
 *   // Search
 *   const results = await SpecVectorIndex.search(outputDir, "email validation", embedSvc);
 */

import { existsSync, readFileSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, basename, dirname } from 'node:path';
import { fileExists } from '../../utils/command-helpers.js';
import type { Embedder } from './embedding-service.js';
import { tokenize, buildBm25Corpus, bm25Score } from './vector-index.js';

// ============================================================================
// TYPES
// ============================================================================

export interface SpecRecord {
  id: string;           // "analyzer.map"
  domain: string;       // "analyzer"
  section: string;      // "requirements" | "purpose" | "entities" | "design" | "architecture" | "other"
  title: string;        // "Requirement: Map" or "Purpose"
  /** Concatenated text used for embedding */
  text: string;
  /** Source files linked to this requirement (from mapping.json) */
  linkedFiles: string;  // JSON-encoded string[] (LanceDB stores as string)
  /** Embedding vector */
  vector: number[];
}

export interface SpecSearchResult {
  record: {
    id: string;
    domain: string;
    section: string;
    title: string;
    text: string;
    /** Parsed from JSON -- list of source file paths linked to this spec section */
    linkedFiles: string[];
  };
  score: number;
}

// ============================================================================
// CONSTANTS
// ============================================================================

const DB_FOLDER = 'vector-index';
const TABLE_NAME = 'specs';

/**
 * Spec-index metadata sidecar, sibling to the LanceDB folder. Separate from the
 * function index's `vector-index-meta.json` so the two tables can have
 * independent embedding states. Source of truth for whether the spec table
 * supports ANN search.
 */
const META_FILE = 'spec-index-meta.json';
const META_SCHEMA_VERSION = 1;

interface SpecIndexMeta {
  hasEmbeddings: boolean;
  dim: number;
  model: string | null;
  builtAt: string;
  schemaVersion: number;
}

function specMetaPath(outputDir: string): string {
  return join(outputDir, META_FILE);
}

/** Read the spec-index meta sidecar. Missing sidecar ⇒ legacy embedded index. */
function readSpecMeta(outputDir: string): SpecIndexMeta | null {
  try {
    return JSON.parse(readFileSync(specMetaPath(outputDir), 'utf-8')) as SpecIndexMeta;
  } catch {
    return null;
  }
}

async function writeSpecMeta(outputDir: string, meta: SpecIndexMeta): Promise<void> {
  await writeFile(specMetaPath(outputDir), JSON.stringify(meta, null, 2) + '\n', 'utf-8');
}

// Mapping entry shape from .openlore/analysis/mapping.json
interface MappingEntry {
  requirement: string;
  service?: string;
  domain: string;
  specFile?: string;
  functions?: Array<{ name: string; file: string; line?: number; kind?: string; confidence?: string }>;
}

// ============================================================================
// MARKDOWN PARSER
// ============================================================================

interface ParsedSection {
  section: string;
  title: string;
  content: string;
  requirementKey?: string; // slugified requirement name for mapping lookup
}

/**
 * Parse a spec Markdown file into logical sections.
 * Each H2 becomes a section; H3 within Requirements becomes individual items.
 */
function parseSpecFile(markdown: string): ParsedSection[] {
  const lines = markdown.split('\n');
  const results: ParsedSection[] = [];

  let currentH2 = '';
  let currentH2Section = '';
  let currentH3 = '';
  let currentH3Key = '';
  let buffer: string[] = [];

  const flush = () => {
    const content = buffer.join('\n').trim();
    if (!content) return;

    if (currentH3 && currentH2Section === 'requirements') {
      results.push({
        section: 'requirements',
        title: currentH3,
        content,
        requirementKey: currentH3Key,
      });
    } else if (currentH2) {
      results.push({
        section: currentH2Section,
        title: currentH2,
        content,
      });
    }
    buffer = [];
  };

  for (const line of lines) {
    // Skip generator comment lines
    if (line.startsWith('> Generated by')) continue;
    if (line.startsWith('> Source files:')) continue;

    const h2Match = line.match(/^## (.+)/);
    const h3Match = line.match(/^### (.+)/);

    if (h2Match) {
      flush();
      currentH2 = h2Match[1].trim();
      currentH2Section = slugifySection(currentH2);
      currentH3 = '';
      currentH3Key = '';
    } else if (h3Match && currentH2Section === 'requirements') {
      flush();
      currentH3 = h3Match[1].trim();
      currentH3Key = slugifyRequirement(currentH3);
    } else if (!line.startsWith('# ')) {
      // Skip H1 (spec title handled by filename/domain)
      buffer.push(line);
    }
  }
  flush();

  return results;
}

function slugifySection(title: string): string {
  const lower = title.toLowerCase();
  if (lower.includes('purpose')) return 'purpose';
  if (lower.includes('entit')) return 'entities';
  if (lower.includes('requirement')) return 'requirements';
  if (lower.includes('design')) return 'design';
  if (lower.includes('architecture')) return 'architecture';
  if (lower.includes('sub-component') || lower.includes('subcomponent')) return 'subcomponents';
  return lower.replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

/** Extract requirement key from "Requirement: MapSomething" -> "mapSomething" */
function slugifyRequirement(title: string): string {
  const withoutPrefix = title.replace(/^Requirement:\s*/i, '').trim();
  // camelCase -> first char lowercase
  return withoutPrefix.charAt(0).toLowerCase() + withoutPrefix.slice(1);
}

// ============================================================================
// MAPPING INDEX
// ============================================================================

/**
 * Build a lookup: "domain:requirementKey" -> string[] of source files.
 * Filters out wildcard entries (*) and deduplicates.
 */
function buildMappingIndex(mappings: MappingEntry[]): Map<string, string[]> {
  const index = new Map<string, string[]>();
  for (const m of mappings) {
    const key = `${m.domain}:${m.requirement}`;
    const files = (m.functions ?? [])
      .map(f => f.file)
      .filter(f => f && f !== '*');
    if (files.length > 0) {
      const existing = index.get(key) ?? [];
      const merged = [...new Set([...existing, ...files])];
      index.set(key, merged);
    }
  }
  return index;
}

// ============================================================================
// TEXT BUILDER
// ============================================================================

function buildText(domain: string, section: ParsedSection): string {
  const parts = [`[spec:${domain}] ${section.title}`];
  if (section.content) parts.push(section.content);
  return parts.join('\n');
}

// ============================================================================
// ADR PARSER
// ============================================================================

interface AdrRecord {
  id: string;
  domain: string;
  section: string;
  title: string;
  text: string;
  linkedFiles: string;
}

async function findAdrFiles(decisionsDir: string): Promise<string[]> {
  if (!(await fileExists(decisionsDir))) return [];
  try {
    const entries = await readdir(decisionsDir);
    return entries
      .filter((f) => /^adr-\d+.*\.md$/i.test(f))
      .map((f) => join(decisionsDir, f));
  } catch {
    return [];
  }
}

async function parseAdrFiles(decisionsDir: string): Promise<AdrRecord[]> {
  const files = await findAdrFiles(decisionsDir);
  const records: AdrRecord[] = [];

  for (const filePath of files) {
    try {
      const content = await readFile(filePath, 'utf-8');
      const titleMatch = content.match(/^#\s+(ADR-\d+):\s+(.+)$/m);
      if (!titleMatch) continue;
      const adrNum = titleMatch[1];
      const title = titleMatch[2].trim();

      records.push({
        id: `decisions.${adrNum.toLowerCase()}`,
        domain: 'decisions',
        section: adrNum,
        title: `${adrNum}: ${title}`,
        text: `[decision] ${adrNum}: ${title}\n${content}`,
        linkedFiles: '[]',
      });
    } catch {
      continue;
    }
  }

  return records;
}

// ============================================================================
// SPEC VECTOR INDEX
// ============================================================================

export class SpecVectorIndex {
  /**
   * Discover all spec.md files under specsDir, parse them, enrich with mapping,
   * embed, and write to LanceDB table "specs".
   *
   * @param outputDir  Path to .openlore/analysis/
   * @param specsDir   Path to openspec/specs/ (or any directory containing domain/spec.md files)
   * @param mappingJsonPath  Path to mapping.json (optional -- no enrichment if absent)
   */
  static async build(
    outputDir: string,
    specsDir: string,
    embedSvc: Embedder | null,
    mappingJsonPath?: string,
    decisionsDir?: string
  ): Promise<{ recordCount: number; hasEmbeddings: boolean }> {
    const { connect } = await import('@lancedb/lancedb');

    // Load mapping index (optional)
    let mappingIndex = new Map<string, string[]>();
    if (mappingJsonPath && await fileExists(mappingJsonPath)) {
      try {
        const raw = JSON.parse(await readFile(mappingJsonPath, 'utf-8'));
        mappingIndex = buildMappingIndex((raw.mappings ?? []) as MappingEntry[]);
      } catch {
        // non-fatal -- proceed without enrichment
      }
    }

    // Discover spec files — distinguish "directory missing" from "directory
    // present but empty" so callers can tell a misconfig from an unseeded repo.
    const specFiles = await findSpecFiles(specsDir);
    if (specFiles.length === 0) {
      const dirExists = await fileExists(specsDir);
      throw new Error(
        dirExists
          ? `Spec directory ${specsDir} exists but contains no spec.md files — run 'openlore generate', or point openspecPath at your specs`
          : `Spec directory ${specsDir} does not exist — run 'openlore init' (it now detects docs/specs/ and specs/)`
      );
    }

    // Parse all specs into records (without vectors)
    const records: Omit<SpecRecord, 'vector'>[] = [];

    for (const specFile of specFiles) {
      const domain = basename(dirname(specFile));
      let markdown: string;
      try {
        markdown = await readFile(specFile, 'utf-8');
      } catch {
        continue;
      }

      const sections = parseSpecFile(markdown);

      for (const sec of sections) {
        const reqKey = sec.requirementKey ?? sec.section;
        const mappingKey = `${domain}:${reqKey}`;
        const linkedFiles = mappingIndex.get(mappingKey) ?? [];

        const id = sec.requirementKey
          ? `${domain}.${sec.requirementKey}`
          : `${domain}.${sec.section}`;

        const text = buildText(domain, sec);

        records.push({
          id,
          domain,
          section: sec.section,
          title: sec.title,
          text,
          linkedFiles: JSON.stringify(linkedFiles),
        });
      }
    }

    // Also index ADR files from openspec/decisions/ if decisionsDir provided
    if (decisionsDir) {
      const adrRecords = await parseAdrFiles(decisionsDir);
      records.push(...adrRecords);
    }

    if (records.length === 0) {
      throw new Error('No spec sections could be parsed');
    }

    const dbPath = join(outputDir, DB_FOLDER);

    // ── BM25-only build (no embedding service) ───────────────────────────────
    // Write records without a `vector` column and record hasEmbeddings:false.
    if (!embedSvc) {
      const db = await connect(dbPath);
      await db.createTable(
        TABLE_NAME,
        records as unknown as Record<string, unknown>[],
        { mode: 'overwrite' }
      );
      await writeSpecMeta(outputDir, {
        hasEmbeddings: false,
        dim: 0,
        model: null,
        builtAt: new Date().toISOString(),
        schemaVersion: META_SCHEMA_VERSION,
      });
      return { recordCount: records.length, hasEmbeddings: false };
    }

    // Batch-embed
    const texts = records.map(r => r.text);
    const vectors = await embedSvc.embed(texts);

    if (vectors.length !== records.length) {
      throw new Error(`Embedding count mismatch: expected ${records.length}, got ${vectors.length}`);
    }

    const fullRecords: SpecRecord[] = records.map((r, i) => ({
      ...r,
      vector: vectors[i],
    }));

    // Write to LanceDB (same DB folder, table "specs")
    const db = await connect(dbPath);
    await db.createTable(TABLE_NAME, fullRecords as unknown as Record<string, unknown>[], { mode: 'overwrite' });

    await writeSpecMeta(outputDir, {
      hasEmbeddings: true,
      dim: fullRecords[0]?.vector.length ?? 0,
      model: embedSvc.modelName,
      builtAt: new Date().toISOString(),
      schemaVersion: META_SCHEMA_VERSION,
    });

    return { recordCount: fullRecords.length, hasEmbeddings: true };
  }

  /**
   * Semantic search over the spec index.
   */
  static async search(
    outputDir: string,
    query: string,
    embedSvc: Embedder | null | undefined,
    opts: {
      limit?: number;
      domain?: string;
      section?: string;
    } = {}
  ): Promise<SpecSearchResult[]> {
    const { connect } = await import('@lancedb/lancedb');

    const { limit = 10, domain, section } = opts;

    if (!SpecVectorIndex.exists(outputDir)) {
      throw new Error('No spec index found. Run "openlore analyze" first.');
    }

    const dbPath = join(outputDir, DB_FOLDER);
    const db = await connect(dbPath);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const table: any = await db.openTable(TABLE_NAME);

    // ── BM25-only path ─────────────────────────────────────────────────────────
    // Force BM25 when no embedder is available OR the spec index was built
    // without embeddings (no `vector` column). Missing sidecar ⇒ legacy embedded.
    const meta = readSpecMeta(outputDir);
    const indexHasEmbeddings = meta === null ? true : meta.hasEmbeddings;
    if (!embedSvc || !indexHasEmbeddings) {
      return SpecVectorIndex._bm25Only(table, query, limit, domain, section);
    }

    const [queryVector] = await embedSvc.embed([query]);
    if (!queryVector) throw new Error('Failed to embed query');

    const fetchLimit = Math.min(limit * 10, 500);
    const rows = await table.query().nearestTo(queryVector).limit(fetchLimit).toArray();

    const filtered = rows
      .filter((row: Record<string, unknown>) => {
        if (domain && (row.domain as string) !== domain) return false;
        if (section && (row.section as string) !== section) return false;
        return true;
      })
      .slice(0, limit);

    return filtered.map((row: Record<string, unknown>) => {
      let linkedFiles: string[] = [];
      try {
        linkedFiles = JSON.parse(row.linkedFiles as string) as string[];
      } catch { /* ignore */ }

      return {
        record: {
          id: row.id as string,
          domain: row.domain as string,
          section: row.section as string,
          title: row.title as string,
          text: row.text as string,
          linkedFiles,
        },
        score: row._distance as number,
      };
    });
  }

  /**
   * BM25-only search over the spec corpus: used when no embedding service is
   * available or the index was built without embeddings. Scores the full
   * corpus with BM25 and returns the top `limit` matching sections.
   */
  private static async _bm25Only(
    table: { query(): { toArray(): Promise<Record<string, unknown>[]> } },
    query: string,
    limit: number,
    domain?: string,
    section?: string,
  ): Promise<SpecSearchResult[]> {
    const allRows = await table.query().toArray() as Record<string, unknown>[];
    const corpus = buildBm25Corpus(
      allRows.map(r => ({ id: r.id as string, text: r.text as string }))
    );
    const queryTokens = tokenize(query);
    const rowById = new Map(allRows.map(r => [r.id as string, r]));

    return corpus.docs
      .map((_, i) => ({ idx: i, score: bm25Score(corpus, queryTokens, i) }))
      .filter(({ score }) => score > 0)
      // Deterministic ordering: score desc, ties broken by id asc.
      .sort((a, b) => b.score - a.score || (corpus.docs[a.idx].id < corpus.docs[b.idx].id ? -1 : 1))
      .map(({ idx, score }) => {
        const row = rowById.get(corpus.docs[idx].id);
        return row ? { row, score } : null;
      })
      .filter((x): x is { row: Record<string, unknown>; score: number } => x !== null)
      .filter(({ row }) => {
        if (domain && (row.domain as string) !== domain) return false;
        if (section && (row.section as string) !== section) return false;
        return true;
      })
      .slice(0, limit)
      .map(({ row, score }) => {
        let linkedFiles: string[] = [];
        try {
          linkedFiles = JSON.parse(row.linkedFiles as string) as string[];
        } catch { /* ignore */ }
        return {
          record: {
            id: row.id as string,
            domain: row.domain as string,
            section: row.section as string,
            title: row.title as string,
            text: row.text as string,
            linkedFiles,
          },
          score,
        };
      });
  }

  /**
   * Returns true if the spec index table exists.
   */
  static exists(outputDir: string): boolean {
    // LanceDB stores each table as a subfolder inside the DB folder
    return existsSync(join(outputDir, DB_FOLDER, `${TABLE_NAME}.lance`));
  }
}

// ============================================================================
// HELPERS
// ============================================================================

async function findSpecFiles(specsDir: string): Promise<string[]> {
  if (!await fileExists(specsDir)) return [];
  const results: string[] = [];

  let entries: string[];
  try {
    entries = await readdir(specsDir);
  } catch {
    return [];
  }

  for (const entry of entries) {
    const domainDir = join(specsDir, entry);
    const specFile = join(domainDir, 'spec.md');
    if (await fileExists(specFile)) {
      results.push(specFile);
    }
  }

  return results;
}
